name: CMake Build

on:
  # Triggers the workflow on push or pull request events
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

  # Runs this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "ubuntu_latest_gcc_boost_on",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "gcc-11",
            cxx: "g++-11",
            boost: "ON",
            coverage: "OFF"
          }
        - {
            name: "ubuntu_latest_gcc_boost_off",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "gcc-11",
            cxx: "g++-11",
            boost: "OFF",
            coverage: "OFF"
          }
        - {
            name: "ubuntu_latest_clang_boost_on",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "clang-10",
            cxx: "clang++-10",
            boost: "ON",
            coverage: "OFF"
          }
        - {
            name: "ubuntu_latest_clang_boost_off",
            os: ubuntu-latest,
            build_type: "Release",
            cc: "clang-10",
            cxx: "clang++-10",
            boost: "OFF",
            coverage: "OFF"
          }
        - {
            name: "ubuntu_latest_code_coverage",
            os: ubuntu-latest,
            build_type: "Debug",
            cc: "clang-10",
            cxx: "clang++-10",
            boost: "OFF",
            coverage: "ON"
          }
        - {
            name: "windows_latest_gcc_boost_off",
            os: windows-latest,
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            boost: "OFF",
            coverage: "OFF"
          }
#        - {
#            name: "windows_latest_clang",
#            os: windows-latest,
#            build_type: "Release",
#            cc: "clang",
#            cxx: "clang++",
#            boost: "OFF",
#            coverage: "OFF"
#          }
          
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
        with:
          submodules: recursive

      - name: Print Event
        run: |
          echo github.event.action: ${{ github.event.action }}
          echo github.event_name: ${{ github.event_name }}
          
      - name: Install Dependencies Linux
        if: startsWith(matrix.config.name, 'ubuntu_latest')
        run: |
          sudo apt-get update
          sudo apt-get install cmake
          sudo apt-get install gcc-11 g++-11
          sudo apt-get install clang-10
          sudo apt-get install lcov
          cmake    --version
          gcc      --version
          gcc-11   --version
          clang-10 --version
          lcov     --version

      - name: Install Dependencies Windows
        if: startsWith(matrix.config.name, 'windows_latest')
        run: |
          cmake    --version
          gcc      --version
          clang    --version
          
      - name: Configure
        shell: bash
        run: |
          rm -rf build
          mkdir build
          cmake \
            -S . \
            -B build \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -DCMAKE_C_COMPILER=${{ matrix.config.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} \
            -DIMPROC_WITH_BOOST=${{ matrix.config.boost }} \
            -DIMPROC_WITH_COVERAGE=${{ matrix.config.coverage }} \
            -DIMPROC_WITH_TESTS=ON \
            -G "Unix Makefiles"
      
      - name: Build
        shell: bash
        run: cmake --build build --config ${{ matrix.config.build_type }} --target all

      - name: Test
        if: ${{ matrix.config.coverage }} == "OFF"
        shell: bash
        run: ./build/bin/improc_infrastructure_test

      - name: Code Coverage
        if: ${{ matrix.config.coverage }} == "ON"
        shell: bash
        run: |
          ./build/bin/improc_infrastructure_testd
          ./build/make coverage

